### PR TITLE
Fix merge conflicts for - second try: Remove findDOMNode #747

### PR DESCRIPTION
**Pull request by jensborch**

### CODE REVIEW

**Comment by jensborch** [comment]
@EmiBemi @b-d-m-p  This need further work, test are failing locally, I would like help on this :-)

**Comment by jensborch** [comment]
@b-d-m-p @EmiBemi I think we should consider changing out unit-test.yml workflow to run on all PR, as we rights now can't see in the PR if test are failing

**Comment by jensborch** [comment]
@b-d-m-p I will close this as it still have conflicts and I have agreed with @EmiBemi that we will make a new PR against "next" instead, as this change isn't related to the v14 update

**Comment by b-d-m-p** [comment]
@jensborch I did think it was strange the original PR was going to this branch. I solved the merge conflicts when merging with master but not this branch it seems. I will make a new one and fix the merge conflicts from there.

**Comment by jensborch** [comment]
@b-d-m-p I think @EmiBemi is looking into that now

**Comment by b-d-m-p** [comment]
@EmiBemi @jensborch there were just two conflicts, package-lock.json and one other one. The other one seemed straight forward, so I fixed it but now the project wont't run, so I'm taking a closer look.

**Comment by b-d-m-p** [comment]
@EmiBemi @jensborch it's the ripple and it looks like it shouldn't be problematic, but the project doesn't run. Haven't figured it out yet. I am going hiking will be back in a little more than 48 hours.

**Comment by b-d-m-p** [comment]
@EmiBemi @jensborch so I looked at the code and did what I thought was needed to fix the merge conflicts and I still got a ton of errors, which made me think "how do I know if next is working properly", so I checked that out and tried to run it and and I got all the same errors, which means the issue is in the next branch and not this one. Let's get the next branch working and then we can try merging this again.

**Comment by EmiBemi** [comment]
@b-d-m-p Next works just fine. I just had to delete node_modules and package-lock and do a clean install.

**Comment by EmiBemi** [comment]
https://github.com/rmwc/rmwc/pull/941 fix for next

**Pull request closed without merging**
